[package]
name = "qfoil-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[[bin]]
name = "qfoil"
path = "src/main.rs"

[dependencies]
qfoil-core.workspace = true
clap.workspace = true

[dev-dependencies]
qfoil-golden.workspace = true

[lints]
workspace = true
