SUBROUTINE PLOPEN(RDUM,IDUM1,IDUM2,IDUM3,IDUM4,IDUM5,IDUM6)
      RETURN
      END
      SUBROUTINE PLOT(RDUM1,RDUM2,IDUM)
      RETURN
      END
      SUBROUTINE PLNUMB(RDUM1,RDUM2,RDUM3,RDUM4,RDUM5,RDUM6,IDUM)
      RETURN
      END
      SUBROUTINE PLSYMB(RDUM1,RDUM2,RDUM3,RDUM4,RDUM5,RDUM6,IDUM)
      RETURN
      END
      SUBROUTINE PLCHAR(RDUM1,RDUM2,RDUM3,RDUM4,RDUM5,IDUM)
      RETURN
      END
      SUBROUTINE PLSLAN(RDUM1)
      RETURN
      END
      SUBROUTINE PLMATH(RDUM1,RDUM2,RDUM3,RDUM4,RDUM5,IDUM)
      RETURN
      END
      SUBROUTINE NEWF(IDUM1,IDUM2,IDUM3,IDUM4,IDUM5)
      RETURN
      END
      SUBROUTINE PLEND
      RETURN
      END
      SUBROUTINE PLRFLU
      RETURN
      END
      SUBROUTINE PLOTABS(RDUM1,RDUM2,IDUM)
      RETURN
      END
!     --- NEW STUBS FOR XFOIL LINKING ---
      SUBROUTINE REPLOT(IDUM)
      RETURN
      END
      SUBROUTINE USETZOOM(RDUM1,RDUM2,RDUM3,RDUM4)
      RETURN
      END
      SUBROUTINE CLRZOOM
      RETURN
      END
      SUBROUTINE PLINITIALIZE
      RETURN
      END
      SUBROUTINE COLORSPECTRUMHUES(IDUM1,RDUM1)
      RETURN
      END
      SUBROUTINE PLCLOSE
      RETURN
      END
      SUBROUTINE NEWPEN(IDUM)
      RETURN
      END
      SUBROUTINE XYLINE(IDUM1,RDUM1,RDUM2,RDUM3,RDUM4,IDUM2)
      RETURN
      END
      SUBROUTINE PLFLUSH
      RETURN
      END
      SUBROUTINE NEWFACTOR(RDUM)
      RETURN
      END
      SUBROUTINE ANNOT(RDUM1,RDUM2,RDUM3,RDUM4,IDUM1,STR)
      CHARACTER*(*) STR
      RETURN
      END
      SUBROUTINE GETCOLOR(IDUM)
      RETURN
      END
      SUBROUTINE GETPAT(IDUM)
      RETURN
      END
      SUBROUTINE NEWCOLORNAME(STR)
      CHARACTER*(*) STR
      RETURN
      END
      SUBROUTINE NEWCOLOR(IDUM)
      RETURN
      END
      SUBROUTINE NEWPAT(IDUM)
      RETURN
      END
      SUBROUTINE GETPEN(IDUM)
      RETURN
      END
      SUBROUTINE AXISADJ(IDUM1,IDUM2,RDUM1,RDUM2,RDUM3)
      RETURN
      END
      SUBROUTINE PLGRID(RDUM1,RDUM2,IDUM1,RDUM3,IDUM2,RDUM4,IDUM3)
      RETURN
      END
      SUBROUTINE XAXIS(RDUM1,RDUM2,RDUM3,RDUM4,RDUM5,RDUM6,RDUM7,IDUM1,IDUM2,STR)
      CHARACTER*(*) STR
      RETURN
      END
      SUBROUTINE YAXIS(RDUM1,RDUM2,RDUM3,RDUM4,RDUM5,RDUM6,RDUM7,IDUM1,IDUM2,STR)
      CHARACTER*(*) STR
      RETURN
      END
      SUBROUTINE GETCURSORXY(RDUM1,RDUM2,IDUM)
      RETURN
      END
      SUBROUTINE GETCURSORXYC(RDUM1,RDUM2,IDUM,CH)
      CHARACTER*1 CH
      RETURN
      END
      SUBROUTINE GETWINSIZE(RDUM1,RDUM2)
      RETURN
      END
      SUBROUTINE NEWCLIPABS(RDUM1,RDUM2,RDUM3,RDUM4)
      RETURN
      END
      SUBROUTINE GETLASTXY(RDUM1,RDUM2)
      RETURN
      END
      SUBROUTINE GETCLIPABS(RDUM1,RDUM2,RDUM3,RDUM4)
      RETURN
      END
      SUBROUTINE CLRCLIP
      RETURN
      END
      SUBROUTINE GETFACTORS(RDUM1,RDUM2)
      RETURN
      END
      SUBROUTINE NEWFACTORS(RDUM1,RDUM2)
      RETURN
      END
      SUBROUTINE GETORIGIN(RDUM1,RDUM2)
      RETURN
      END
      SUBROUTINE GETCLIP(RDUM1,RDUM2,RDUM3,RDUM4)
      RETURN
      END
      SUBROUTINE NEWCLIP(RDUM1,RDUM2,RDUM3,RDUM4)
      RETURN
      END
      SUBROUTINE XYSYMB(RDUM1,RDUM2,RDUM3,IDUM1,RDUM4,IDUM2)
      RETURN
      END
      SUBROUTINE GETCOLORRGB(IDUM, RDUM1, RDUM2, RDUM3)
      RETURN
      END
      SUBROUTINE NEWCOLORRGB(IDUM, RDUM1, RDUM2, RDUM3)
      RETURN
      END